// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	BeBundleElement string
	BuBundle        string
	OpOption        string
	PRProduct       string
	STStock         string
	WaWarehouse     string
}{
	BeBundleElement: "be_bundle_element",
	BuBundle:        "bu_bundle",
	OpOption:        "op_option",
	PRProduct:       "pr_product",
	STStock:         "st_stock",
	WaWarehouse:     "wa_warehouse",
}
